name: arthurs_app
description: A sample Polymer application
dependencies:
  core_elements: '>=0.1.0 <0.2.0'
  paper_elements: '>=0.1.0 <0.2.0'
  polymer: '>=0.12.0 <0.13.0'
  template_binding: any
transformers:
- polymer:
    entry_points: web/arthurs_app.html
